
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Bai80 extends javax.swing.JFrame {

    /**
     * Creates new form Bai80
     */
    public Bai80() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtKQ = new javax.swing.JTextField();
        bnTinh = new javax.swing.JButton();
        txtLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Giải Phương Trình ax + b = 0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel2.setText("Nhập b");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setText("Kết Quả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel4.setText("Nhập a");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 80, -1));
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));
        getContentPane().add(txtKQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, -1));

        bnTinh.setText("Tính");
        bnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(bnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtLai.setText("Nhập lại");
        txtLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnTinhActionPerformed
        String a = txtA.getText();
        String b = txtB.getText();
        double sa=0,sb=0,x=0;
        try
        {
            sa = Double.parseDouble(a);
            sb = Double.parseDouble(b);
        }
        catch(Exception ex)
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng nhập số!");
        }
        if(sa==0 && sb==0)
        {
            txtKQ.setText("Vô Số Nghiệm!");
        }
        if(sa==0&&sb!=0)
        {
            txtKQ.setText("Vô Nghiệm!");
        }
        if(sa!=0&&sb!=0)
        {
            x = -sb/sa;
            txtKQ.setText(String.valueOf(x));
        }
        
    }//GEN-LAST:event_bnTinhActionPerformed

    private void txtLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaiActionPerformed
        txtA.setText("");
        txtB.setText("");
        txtKQ.setText("");
    }//GEN-LAST:event_txtLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai80.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai80.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai80.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai80.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai80().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKQ;
    private javax.swing.JButton txtLai;
    // End of variables declaration//GEN-END:variables
}
