
import java.awt.Color;
import java.awt.Container;
import java.awt.MenuComponent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.AncestorListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Bai85 extends javax.swing.JFrame {
    /**
     * Creates new form Bai85
     */
    DefaultListModel dm = new DefaultListModel();
    public Bai85() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PPhai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        bnXoa = new javax.swing.JButton();
        bnSua = new javax.swing.JButton();
        bnThem = new javax.swing.JButton();
        PTrai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSTen = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PPhai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PPhaiMouseClicked(evt);
            }
        });
        PPhai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Input Name");
        PPhai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        PPhai.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        bnXoa.setText("Remove");
        bnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXoaActionPerformed(evt);
            }
        });
        PPhai.add(bnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        bnSua.setText("Edit");
        bnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSuaActionPerformed(evt);
            }
        });
        PPhai.add(bnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        bnThem.setText("ADD");
        bnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnThemActionPerformed(evt);
            }
        });
        PPhai.add(bnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(PPhai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 293, 298));

        DSTen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(DSTen);

        javax.swing.GroupLayout PTraiLayout = new javax.swing.GroupLayout(PTrai);
        PTrai.setLayout(PTraiLayout);
        PTraiLayout.setHorizontalGroup(
            PTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTraiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PTraiLayout.setVerticalGroup(
            PTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTraiLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getContentPane().add(PTrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void bnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnThemActionPerformed
//        ListModel dsTen = DSTen.getModel();
//        String[] mTen = new String[dsTen.getSize()+1];
//        int i = 0;
//        for(i=0;i<dsTen.getSize();i++)
//        {
//            mTen[i] = dsTen.getElementAt(i).toString();
//            
//        }
//        mTen[i] = txtTen.getText();
//        DSTen.setListData(mTen);
        dm.addElement(txtTen.getText());
        DSTen.setModel(dm);
        txtTen.setText("");
    }//GEN-LAST:event_bnThemActionPerformed

    private void bnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXoaActionPerformed

        int stt = DSTen.getSelectedIndex();
        dm.removeElementAt(stt);
        txtTen.setText("");
    }//GEN-LAST:event_bnXoaActionPerformed

    private void PPhaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPhaiMouseClicked
//        String a = DSTen.getSelectedValue().toString();
//        txtTen.setText(a);
    }//GEN-LAST:event_PPhaiMouseClicked

    private void bnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSuaActionPerformed
        int stt = DSTen.getSelectedIndex();
        dm.setElementAt(txtTen.getText(), stt);
        txtTen.setText("");
    }//GEN-LAST:event_bnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai85.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai85.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai85.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai85.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai85().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> DSTen;
    private javax.swing.JPanel PPhai;
    private javax.swing.JPanel PTrai;
    private javax.swing.JButton bnSua;
    private javax.swing.JButton bnThem;
    private javax.swing.JButton bnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
