import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class BaiTH3 extends javax.swing.JFrame {
    
    /**
     * Creates new form BaiTH3
     */
    
    DefaultListModel mTrai=new DefaultListModel();
    DefaultListModel mPhai=new DefaultListModel();
    
    public BaiTH3() {
        initComponents();
        LTrai.setModel(mTrai);

        mTrai.addElement("Bóng Đá");
        mTrai.addElement("Cầu lông");
        mTrai.addElement("Karatedo");
        mTrai.addElement("Bóng chuyền");

        mPhai.addElement("Bóng Đá");
        LPhai.setModel(mPhai);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LPhai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LTrai = new javax.swing.JList<>();
        bnAllTrai = new javax.swing.JButton();
        bn1Phai = new javax.swing.JButton();
        bn1Trai = new javax.swing.JButton();
        bnAllPhai = new javax.swing.JButton();
        bnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(LPhai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, 170));

        jScrollPane2.setViewportView(LTrai);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 92, 120, 170));

        bnAllTrai.setText(">>");
        bnAllTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAllTraiActionPerformed(evt);
            }
        });
        getContentPane().add(bnAllTrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        bn1Phai.setText("<");
        bn1Phai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1PhaiActionPerformed(evt);
            }
        });
        getContentPane().add(bn1Phai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        bn1Trai.setText(">");
        bn1Trai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn1TraiActionPerformed(evt);
            }
        });
        getContentPane().add(bn1Trai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        bnAllPhai.setText("<<");
        bnAllPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAllPhaiActionPerformed(evt);
            }
        });
        getContentPane().add(bnAllPhai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        bnThem.setText("Thêm");
        bnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnThemActionPerformed(evt);
            }
        });
        getContentPane().add(bnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel1.setText("Môn Yêu Thích");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel2.setText("DS Môn Thể Thao");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn1TraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1TraiActionPerformed
        
        int j[] = LTrai.getSelectedIndices();
        
        for(int i = j.length-1;i>=0;i--)
        {
            if(mTrai==mPhai)
            {
                mTrai.remove(j[i]);
            }
            else{
                mPhai.addElement(mTrai.get(j[i]));
                mTrai.remove(j[i]);

            }
        }
        
    }//GEN-LAST:event_bn1TraiActionPerformed

    private void bnAllTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAllTraiActionPerformed

    int m = mTrai.getSize();
    for (int i = 0; i < m; i++)
        {
            mPhai.addElement(mTrai.get(i));
        }
            mTrai.clear();
        
        
        
        
    }//GEN-LAST:event_bnAllTraiActionPerformed

    private void bnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnThemActionPerformed
        String Them = JOptionPane.showInputDialog("Môn thể thao: ");
        mTrai.addElement(Them);
        
// TODO add your handling code here:
    }//GEN-LAST:event_bnThemActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void bn1PhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn1PhaiActionPerformed
        int j[] = LPhai.getSelectedIndices();
        for(int i = j.length-1;i>=0;i--)
        {
            mTrai.addElement(mPhai.get(j[i]));
            mPhai.remove(j[i]);
        }
        
        
        
    }//GEN-LAST:event_bn1PhaiActionPerformed

    private void bnAllPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAllPhaiActionPerformed
        int n = mPhai.getSize();
        for(int i = 0; i < n;i++)
        {
            mTrai.addElement(mPhai.get(i));
        }
        mPhai.clear();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bnAllPhaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTH3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTH3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTH3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTH3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiTH3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LPhai;
    private javax.swing.JList<String> LTrai;
    private javax.swing.JButton bn1Phai;
    private javax.swing.JButton bn1Trai;
    private javax.swing.JButton bnAllPhai;
    private javax.swing.JButton bnAllTrai;
    private javax.swing.JButton bnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
