/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.XuLy;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class NhomSanPhamForm extends javax.swing.JFrame {

    /**
     * Creates new form NhomSanPhamForm
     */
    public NhomSanPhamForm() {
        initComponents();
        tbNSP.setModel(XuLy.NhomSanPhamModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTNSP = new javax.swing.JTextField();
        txtMNSP = new javax.swing.JTextField();
        bnXoa = new javax.swing.JButton();
        bnThoat = new javax.swing.JButton();
        bnSua = new javax.swing.JButton();
        bnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNSP = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Mã NSP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(txtTNSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));
        getContentPane().add(txtMNSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, -1));

        bnXoa.setText("Xóa");
        bnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(bnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        bnThoat.setText("Thoát");
        getContentPane().add(bnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        bnSua.setText("Sửa");
        bnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(bnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        bnThem.setText("Thêm");
        bnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnThemActionPerformed(evt);
            }
        });
        getContentPane().add(bnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tbNSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbNSP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 207, 400, 90));

        jLabel3.setText("Tên NSP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXoaActionPerformed
        int n = tbNSP.getSelectedRow();
        String MaNSP = XuLy.NhomSanPhamModel().getValueAt(n+1,0).toString();
        int thucThi = XuLy.DeleteNhomSanPham(MaNSP);
        if(thucThi == 0){
            JOptionPane.showMessageDialog(rootPane, "Xóa bị lỗi","Lỗi:",JOptionPane.ERROR_MESSAGE);
        }
        tbNSP.setModel(XuLy.NhomSanPhamModel());
    }//GEN-LAST:event_bnXoaActionPerformed

    private void bnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSuaActionPerformed
        XuLy.UpdateNhomSanPham(txtMNSP.getText(),txtTNSP.getText());
        tbNSP.setModel(XuLy.NhomSanPhamModel());
        // TODO add your handling code here:
    }//GEN-LAST:event_bnSuaActionPerformed

    private void bnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnThemActionPerformed
        // TODO add your handling code h
        XuLy.InsertNhomSanPham(String.valueOf(txtMNSP.getText()),String.valueOf(txtTNSP.getText()));
        tbNSP.setModel(XuLy.NhomSanPhamModel());
    }//GEN-LAST:event_bnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhomSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhomSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhomSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhomSanPhamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhomSanPhamForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnSua;
    private javax.swing.JButton bnThem;
    private javax.swing.JButton bnThoat;
    private javax.swing.JButton bnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNSP;
    private javax.swing.JTextField txtMNSP;
    private javax.swing.JTextField txtTNSP;
    // End of variables declaration//GEN-END:variables
}
